apiVersion: v1
kind: Service
metadata:
  namespace: argocd-production
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: <#if isRemote>LoadBalancer<#else>NodePort</#if>
  ports:
    - name: http
      port: 80
      nodePort: 30021
      targetPort: http
  selector:
    app: spring-petclinic-plain
