apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: scmm
  namespace: default
spec:
#  repo: https://packages.scm-manager.org/repository/helm-v2-releases/
  chart: https://%{KUBERNETES_API}%/static/charts/scm-manager-2.7.1.tgz
#  version: 2.7.0
  targetNamespace: default
  set:
    service.port: 9091
  valuesContent: |-
    extraEnvFrom: |
      - prefix: JENKINS_
        secretRef:
          name: jenkins-scmm

    lifecycleHooks: |-
      postStart:
        exec:
          command:
            - "/bin/bash"
            - "-c"
            - >
              set -o errexit -o nounset -o pipefail
              #set -x

              SCM_USER=scmadmin
              SCM_PWD=scmadmin
              HOST=localhost:8080

              function main() {

                cd /tmp && wget https://github.com/dtschan/curl-static/releases/download/v7.63.0/curl && chmod +x curl
                while [[ "$(./curl -s -L -o /dev/null -w ''%{http_code}'' "http://${HOST}/scm")" -ne "200" ]]; do sleep 5; done;

                setConfig "namespaceStrategy" "CustomNamespaceStrategy"
                addRepo "cluster" "gitops"
                addUser "${JENKINS_USERNAME}" "${JENKINS_PASSWORD}" "jenkins@mail.de"
                setPermission "cluster" "gitops" "${JENKINS_USERNAME}" "WRITE"

                rm curl
              }

              function addRepo() {
                ./curl -i -L -X POST -H "Content-Type: application/vnd.scmm-repository+json;v=2" \
                  --data "{\"name\":\"${2}\",\"namespace\":\"${1}\",\"type\":\"git\",\"contact\":\"admin@mail.de\",\"description\":\"description\",\"contextEntries\":{},\"_links\":{}}" \
                  "http://${SCM_USER}:${SCM_PWD}@${HOST}/scm/api/v2/repositories"
              }

              function setConfig() {
                ./curl -i -L -X PUT -H "Content-Type: application/vnd.scmm-config+json;v=2" \
                  --data "{\"${1}\": \"${2}\"}" \
                  "http://${SCM_USER}:${SCM_PWD}@${HOST}/scm/api/v2/config"
              }

              function addUser() {
                ./curl -i -L -X POST -H "Content-Type: application/vnd.scmm-user+json;v=2" \
                  --data "{\"name\":\"${1}\",\"displayName\":\"${1}\",\"mail\":\"${3}\",\"password\":\"${2}\",\"active\":true,\"_links\":{}}" \
                  "http://${SCM_USER}:${SCM_PWD}@${HOST}/scm/api/v2/users"
              }

              function setPermission() {
                ./curl -i -L -X POST -H "Content-Type: application/vnd.scmm-repositoryPermission+json" \
                  --data "{\"name\":\"${3}\",\"role\":\"${4}\",\"verbs\":[],\"groupPermission\":false}" \
                  "http://${SCM_USER}:${SCM_PWD}@${HOST}/scm/api/v2/repositories/${1}/${2}/permissions/"
              }

              main "$@"; exit