service:
  port: 80
  nodePort: 9091

persistence:
  size: 1Gi

extraEnvFrom: |
  - prefix: GITOPS_
    secretRef:
      name: gitops-scmm
  - prefix: ADMIN_
    secretRef:
      name: scmm-credentials