service:
  port: 80
  nodePort: 30022

<#if exampleApps.petclinic.baseDomain?has_content>
ingress:
  hosts:
    - host: staging.petclinic-helm.${exampleApps.petclinic.baseDomain}
      paths: ['/']
</#if>
