extraEnv: |
  - name: TZ
    value: Europe/Berlin

service:
  type: LoadBalancer

ingress:
  enabled: false

# this is a helm chart dependency
podinfo:
  ui:
    color: '#456456'

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 650Mi
