service:
  port: 80
  nodePort: 30023

<#if exampleApps.petclinic.baseDomain?has_content>
ingress:
  hosts:
    - host: production.petclinic-helm.${exampleApps.petclinic.baseDomain}
      paths: ['/']
</#if>
