defaultRules:
  rules:
    alertmanager: true
    etcd: false
    general: true
    k8s: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverError: false
    kubeApiserverSlos: false
    kubelet: false
    kubePrometheusGeneral: true
    kubePrometheusNodeAlerting: false
    kubePrometheusNodeRecording: false
    kubernetesAbsent: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    node: false
    prometheus: true
    prometheusOperator: true
    time: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  enabled: true
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
alertmanager:
  enabled: false
grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: "9095"
  sidecar:
    dashboards:
      #this needs to be added so that the label will become 'label: grafana_dashboards: "1"'
      labelValue: 1
      searchNamespace: "ALL"
  notifiers:
    notifiers.yaml:
      notifiers:
      - name: mailhog
        type: email
        uid: email1
        is_default: true
        settings:
          addresses: alerts@cloudogu.com
          uploadImage: false
  env:
    GF_SMTP_ENABLED: true
    GF_SMTP_FROM_ADDRESS: grafana-alerts@cloudogu.com
    GF_SMTP_HOST: mailhog.monitoring.svc.cluster.local:1025
