apiVersion: v1
kind: Service
metadata:
  namespace: fluxv1-production
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 9001
      targetPort: http
  selector:
    app: spring-petclinic-plain
