extraEnv: |
  - name: TZ
    value: Europe/Berlin
service:
  type: <%= isRemote ? "LoadBalancer" : "NodePort" %>

ingress:
  enabled: false

# this is a helm chart dependency
podinfo:
  ui:
    color: '#456456'
