apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: playground
  namespace: default
spec:
  description: playground project
  destinations:
  - namespace: argocd-production
    server: https://kubernetes.default.svc
  - namespace: argocd-staging
    server: https://kubernetes.default.svc
  sourceRepos:
  - http://scmm-scm-manager.default.svc.cluster.local:9091/scm/repo/argocd/gitops
  - http://scmm-scm-manager.default.svc.cluster.local:9091/scm/repo/argocd/nginx-helm
  - https://charts.bitnami.com/bitnami
