# We don't use staticSiteConfigmap, so this is extensible for our secret example. See ArgoCD.groovy
extraVolumes:
  - name: index
    configMap:
      name: index-nginx
      items:
        - key: index.html
          path: index.html
  - name: secret
    secret:
      secretName: nginx-helm-jenkins
      items:
        - key: some-secret
          path: index.html
extraVolumeMounts: 
  - name: index
    mountPath: /app
    readOnly: true
  - name: secret
    mountPath: /app/secret
    readOnly: true