apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-nginx-helm
  namespace: argocd-staging
spec:
  destination:
    namespace: argocd-staging
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: appps/exercise-nginx-helm/staging
    repoURL: ${scmm.baseUrl}/repo/${namePrefix}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-nginx-helm
  namespace: argocd-production
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/exercise-nginx-helm/production
    repoURL: ${scmm.baseUrl}/repo/${namePrefix}argocd/example-apps
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
