apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: monitoring and alerting stack including prometheus + grafana + argocd notifications
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://codecentric.github.io/helm-charts
    - https://github.com/argoproj/argo-helm/
