apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argo-project
  source:
    path: .
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/control-app
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: false # is set to false to prevent projects to be deleted by accident
      selfHeal: true
