apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    # Name of secret to be created
    name: example-secret
  data:
    - secretKey: some-secret # Key within target secret
      remoteRef:
        key: secret/staging
        property: nginx-secret
