apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: ${namePrefix}argocd
  annotations:
<#if mail.active == true>
  <#if argocd.emailToAdmin?has_content>
    notifications.argoproj.io/subscribe.email: ${argocd.emailToAdmin}
  <#else>
    notifications.argoproj.io/subscribe.email: infra@example.org
  </#if>
</#if>
spec:
  description: Default fallback AppProject if none other is specified. Is not allowed to do anything.
  clusterResourceWhitelist:
  destinations:
  sourceRepos:
  sourceNamespaces:
