apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx
  namespace: argocd
  annotations:
##  every application in this project is going to be notified about when one of these three events trigger
#    notifications.argoproj.io/subscribe.on-sync-status-longer-10s.email: hello@cloudogu.com
#    notifications.argoproj.io/subscribe.on-health-degraded.email: hello@cloudogu.com
#    notifications.argoproj.io/subscribe.on-sync-status-unknown.email: hello@cloudogu.com
#    notifications.argoproj.io/subscribe.on-sync-failed.email: hello@cloudogu.com
spec:
  description: nginx project
  destinations:
  - namespace: argocd-production
    server: https://kubernetes.default.svc
  - namespace: argocd-staging
    server: https://kubernetes.default.svc
  sourceRepos:
  - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
  - https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/nginx-helm-dependency
