apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petclinic
  namespace: argocd
  annotations:
spec:
  description: petclinic project
  destinations:
  - namespace: argocd-production
    server: https://kubernetes.default.svc
  - namespace: argocd-staging
    server: https://kubernetes.default.svc
  sourceRepos:
  - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
