## Server
server:
  ## Server service configuration
  service:
    type: LoadBalancer
    # Actual "nodePort" number cannot be set via the helm chart. 
    # So we use LB for k3s and set well-know port numbers for remote cluster via apply.sh.
    servicePortHttp: 9092
    servicePortHttps: 9093
    
  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  config:
    repositories: |
      - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/control-app
        passwordSecret:
          name: gitops-scmm
          key: PASSWORD
        usernameSecret:
          name: gitops-scmm
          key: USERNAME
  additionalApplications:
    - name: control-app
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      project: default
      source:
        repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/control-app
        targetRevision: HEAD
        path: .
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true