## Server
server:
  ## Server service configuration
  service:
    type: LoadBalancer
    # Is ignored when type is LoadBalancer. For local cluster we change the service type to NodePort
    nodePortHttp: 9092
    nodePortHttps: 9093
