## Server
server:
  ## Server service configuration
  service:
    type: LoadBalancer
    # nodePort cannot be set via the helm chart, so they are set via apply.sh for local cluster

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  config:
    repositories: |
      - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
        passwordSecret:
          name: gitops-scmm
          key: PASSWORD
        usernameSecret:
          name: gitops-scmm
          key: USERNAME
      - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/nginx-helm
        passwordSecret:
          name: gitops-scmm
          key: PASSWORD
        usernameSecret:
          name: gitops-scmm
          key: USERNAME
      - type: helm
        url: https://charts.bitnami.com/bitnami
        name: bitnami
