extraEnv: |
  - name: TZ
    value: Europe/Berlin

service:
  type: LoadBalancer

ingress:
  enabled: false

# this is a helm chart dependency
podinfo:
  ui:
    color: '#456456'

resources:
  limits:
    memory: 750Mi
  requests:
    memory: 750Mi