# Note that many things are disabled here, because we want to start small, especially in airgapped envs where each image
# has to be replicated individually
defaultRules:
  rules:
    alertmanager: true
    etcd: false
    general: true
    k8s: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubelet: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: false
    kubernetesAbsent: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: true
    prometheusOperator: true
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false
  tls:
    # Once admissionWebhooks is disabled, the operator fails with
    # MountVolume.SetUp failed for volume "tls-secret" : secret "...-kube-prometh-admission" not found
    # This can be worked around by disabling tls altogether
    enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
alertmanager:
  enabled: false
grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: "9095"
  sidecar:
    dashboards:
      #this needs to be added so that the label will become 'label: grafana_dashboards: "1"'
      labelValue: 1
      searchNamespace: "ALL"
  notifiers:
    notifiers.yaml:
      notifiers:
      - name: mailhog
        type: email
        uid: email1
        is_default: true
        settings:
          addresses: alerts@cloudogu.com
          uploadImage: false
  env:
    GF_SMTP_ENABLED: true
    GF_SMTP_FROM_ADDRESS: grafana-alerts@cloudogu.com
    GF_SMTP_HOST: mailhog.${namePrefix}monitoring.svc.cluster.local:1025
