apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
      passwordSecret:
        name: gitops-scmm
        key: PASSWORD
      usernameSecret:
        name: gitops-scmm
        key: USERNAME
    - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/control-app
      passwordSecret:
        name: gitops-scmm
        key: PASSWORD
      usernameSecret:
        name: gitops-scmm
        key: USERNAME
    - url: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/nginx-helm
      passwordSecret:
        name: gitops-scmm
        key: PASSWORD
      usernameSecret:
        name: gitops-scmm
        key: USERNAME
    - type: helm
      url: https://charts.bitnami.com/bitnami
      name: bitnami