apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flux-operator
  namespace: default
spec:
  repo: https://charts.fluxcd.io
  chart: flux
  version: 1.3.0
  targetNamespace: default
  valuesContent: |-
    env:
      secretName: flux-scmm
    git:
      url: "http://$(USERNAME):$(PASSWORD)@scmm-scm-manager:9091/scm/repo/cluster/gitops"
      readonly: true
    registry:
      disableScanning: true
    prometheus:
      enabled: false
