namespaceOverride: ${namePrefix}example-apps-staging
service:
  nodePorts:
    http: 30024

<#if exampleApps.nginx.baseDomain?has_content>
ingress:
  enabled: true
  pathType: Prefix
  hostname: staging.nginx-helm.${exampleApps.nginx.baseDomain}
</#if>
