service:
  type: <#if isRemote>LoadBalancer<#else>NodePort</#if>
  port:
    http: 80
  nodePort:
    http: "9094"
auth:
  enabled: true
  fileName: auth.txt
  fileContents: "${username}:${passwordCrypt}"

resources:
  limits:
    memory: 20Mi
    cpu: 500m
  requests:
    memory: 10Mi
    cpu: 20m

ingress:
  enabled: true
<#if mail.url??>
  hosts:
    - host: ${mail.url.host}
<#else>
  hosts:
    - host: mailhog.localhost
</#if>
      paths:
        - path: "/"
          pathType: Prefix
