service:
  type: <#if isRemote>LoadBalancer<#else>NodePort</#if>
  port:
    http: 80
  nodePort:
    http: "9094"
auth:
  enabled: true
  fileName: auth.txt
  fileContents: "${username}:${passwordCrypt}"

resources:
  limits:
    memory: 20Mi
    cpu: 500m
  requests:
    memory: 10Mi
    cpu: 20m

<#if mail.url?has_content>
ingress:
  enabled: true
  hosts:
    - host: ${mail.url}
      paths:
        - path: "/"
          pathType: Prefix
</#if>
