apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-petclinic-helm-staging
  namespace: argocd
spec:
  destination:
    namespace: argocd-staging
    server: https://kubernetes.default.svc
  project: exercises
  source:
    path: staging/exercise-spring-petclinic-helm
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
