apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-petclinic-plain-argo-alerts-production
  namespace: argocd
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: exercises
  source:
    path: production/exercise-spring-petclinic-plain-argo-alerts
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/gitops
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
