apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-production
  namespace: argocd
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: nginx
  source:
    path: .
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/nginx-helm
    targetRevision: main
  syncPolicy:
    automated: {}
